Kanika637/amazon-clone

src/Product.css
src/Product.js

Hey @Kanika637 I improved the UI of the button to make it look presentable and also added a hover effect. Kindly review it

Modified the button UI and added a hover effect to make it presentable

---

src/CheckoutProduct.css

There are 2 commits in this PR ,the later one corrects the  autoformat setting I had in VScode . I apologise for not paying attention  to my commit.

Fixed the spacing issue in #13

---

src/Product.css

Added cursor: pointer style to the product__button: hover class in the src/Product.css file

Style: Changed cursor to pointer #28 

---

src/Header.css

I have added the requested changes to the logo.
The new logo: 
The old logo:

Add the requested changes to the logo for a better UI

---

public/index.html
src/App.js
src/Home.js
src/Navbar.css
src/Navbar.js
src/Product.js

Navbar added as per your requirments
=> Output

navbar added

---

src/Header.js

cart icon updated

---

README.md

Hey @Kanika637, I have fixed some spellings in the readme doc. Please review it.
#63 Issue

Docs: Fixed some typos in ReadMe [issue #63]

---

src/Navbar.css
src/Navbar.js

hey @Jai-Solania-29 , is it fine now

Updated the navbar

---

Dockerfile
docker-compose.yaml

added the docker and docker compose file.
it is working fine.
use `docker-compose up -d --build` to run.

#54 containerize project

---

src/Checkout.css
src/Checkout.js
src/CheckoutProduct.css
src/CheckoutProduct.js
src/Subtotal.js

Changed Checkout Page

---

src/Home.css

What?
Make product card responsive
Why?
Not responsive in mobile view
How?
adding a media query specifically a flex wrap within max-width of 800 pixels

style: make product card responsive

---

src/Header.css
yarn.lock

Fixed header

---

README.md

What:
Fixed issue#88 and updated `README.md` and added the 'table of contents' section.
Screenshot:

Fix: Updated readme.md

---

.gitpod.yml
README.md
src/Footer.js
src/footer.css

#93 Add "Open with Gitpod" Integration

---

.github/workflows/build.yml
yarn.lock

- https://github.com/Kanika637/amazon-clone/issues/74
@Kanika637 please test it the build is failing although build workflows is correct

Automate build testing using github actions

---

src/Checkout.js
src/Navbar.css
src/Navbar.js
yarn.lock

fixed: #84 improve the navbar

---

src/Checkout.css
src/CheckoutProduct.js
src/Subtotal.css
src/Subtotal.js
src/assets/tick.svg

Hi @Kanika637 
Description:
Shopping cart page button and gift card style fixed
Closes #110 
Screenshot:

Issue 110 fixed

---

src/Header.css
src/HeaderSearchBar.js

Implemented dynamic select-bar which resizes based on the selected category
[922ce9d4-74ec-4fe8-b49e-bfde0de74add.webm](https://user-images.githubusercontent.com/65649182/195305807-e7db5740-c904-4f73-a979-48e956dac6c3.webm)
Fixes #46

#46-Navbar functionality implemetation

---

package-lock.json
src/Categories/AllCategories.css

alignment issue resolved in categories

---

src/Home.js

resolved issue #108 
Screenshots :

Updated missing product's information

---

src/Login.js

Hey! @Kanika637  I have made a pull request according to your suggestion. Sorry, I made a commit and pushed it before reading the commit guidelines.

Option for Login with Mobile Number removed

---

src/Checkout.css

issue #132 
SubTotal Container's position is now static .

fixes:issue#132

---

.prettierignore
.prettierrc

add prettier config file

---

src/Categories/AllCategories.js
src/Navbar.js

#105-'change class to className in Navbar.js and AllCategories.js

#105-'change class'_to_'className'_in_Navbar.js_and_AllCategories.js

---

src/Login.js

Fixes:  #147 
In this project as to go at Terms and Conditions Link tag is used which is preferable to use if the page is included in the project but for an external link anchor tag is more suitable.
---
https://www.loom.com/share/adccef5563944f88ae8c5d8087632cff

fix : Broken Link Repaired

---

README.md
src/SideNav.css

Fixes:  #149 
Side bar Head is overlapping with sidebar body hence it is causing problem to close the Side Navbar. 
---
Before
After

#149 side nav closing

---

src/Home.css
src/Home.js

Hey, @Kanika637. I have added the **"Show More Products"** button to the home section. You can review it now.
- Issue: #142 
https://user-images.githubusercontent.com/91705825/197398221-d2d65686-a270-4ce6-a251-a1fa19de0d38.mp4

#142 Show more products, button

---

src/App.js
src/Header.js
src/HeaderSearchBar.js
src/Home.css
src/Home.js
src/ProductData.js

Fixes:  #56
To add Search Functionality I have to change the basic programming of the clone project.
1. The main problem is that you have to store the Product details in some kind of data type like an array so that we can filter that array according to our search input.  So, I have made a different file Called ProductData.js in which I have stored all the product data.
2. After storing the data in an array of objects form I have to change Home.css because this project was using the flex method and dividing the products into parts of three but now I have to convert them into a form of grid.
https://www.loom.com/share/bdd5a7a031654efebfb465ea3d5310c8
---

#56 search functionality

---

src/Categories/BooksToys/BookToys.css
src/Categories/BooksToys/BookToys.js
src/Categories/Electronics/Electronics.css
src/Categories/Electronics/Electronics.js
src/Categories/FashionBeauty/FashionBeauty.css
src/Categories/FashionBeauty/FashionBeauty.js

Dynamically rendered the products in "shop by category " section.
Fixes:  #152 
---

feat: dynamic rendering of products

---

.gitignore
src/components/header/Header.css
src/components/header/Header.js

Fixes:  #158 
---
when user is logged out
when user user is logged in

Sign in button for few seconds

---

Dockerfile
dev/deployment.yaml
dev/service.yaml

I have updated the deployment.yaml and service.yaml files and now they are functioning well.
Fixes:  #169 
- [] Bug fix (non-breaking change which fixes an issue)
- [] I have made corresponding changes to the documentation.
---

Kubernetes Deployment Added

---

src/App.js
src/pages/login/Login.js
src/pages/signup/Signup.css
src/pages/signup/Signup.js

Fix : https://github.com/Kanika637/amazon-clone/issues/166
I have included the signup page and changed specific route for that page in App.js and also Changed the login page for redirection
signup page:
login page (small changes):

signup page for amazon clone
